# Crafty Controller 4.0 - Lint & Build Pipes
# [Maintainer: Zedifus(https://gitlab.com/Zedifus)]
###################################################
---
stages:
  - lint
  - test
  - build-and-deploy
  - release

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  SECRET_DETECTION_EXCLUDED_PATHS: migrations, vendors

include:
  - local: .gitlab/lint.yml
  - local: .gitlab/docker-build.yml
  - local: .gitlab/windows-build.yml
  - local: .gitlab/release.yml
  - component: $CI_SERVER_FQDN/components/secret-detection/secret-detection@main
    rules:
      - if: "$CODE_QUALITY_DISABLED"
        when: never
      - if: $CI_PIPELINE_SOURCE == "schedule"
        when: never
  - component: $CI_SERVER_FQDN/components/sast/sast@main
    inputs:
      excluded_paths: spec, test, tests, tmp, migrations, vendors
      excluded_analyzers: semgrep
    rules:
      - if: "$CODE_QUALITY_DISABLED"
        when: never
      - if: $CI_PIPELINE_SOURCE == "schedule"
        when: never
  - component: $CI_SERVER_FQDN/components/dependency-scanning/main@main
    rules:
      - if: "$CODE_QUALITY_DISABLED"
        when: never
      - if: $CI_PIPELINE_SOURCE == "schedule"
        when: never
