# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    """
    Write your migrations here.
    """
    migrator.add_columns("backups", backup_type=peewee.CharField(default="zip_vault"))


def rollback(migrator, database, **kwargs):
    """
    Write your rollback migrations here.
    """
    migrator.drop_columns("backups", ["backup_type"])
