# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("backups", snapshot=peewee.BooleanField(default=False))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("backups", ["snapshot"])
    """
    Write your rollback migrations here.
    """


5
