# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("users", lang_dir=peewee.CharField(default="ltr"))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("users", ["lang_dir"])
    """
    Write your rollback migrations here.
    """
