# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("roles", mfa_required=peewee.BooleanField(default=False))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("roles", ["mfa_required"])
    """
    Write your rollback migrations here.
    """
