# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("servers", update_watcher=peewee.BooleanField(default=False))
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("servers", ["update_watcher"])
    """
    Write your rollback migrations here.
    """
