# Generated by database migrator
import peewee
import datetime


def migrate(migrator, database, **kwargs):
    db = database

    class Users(peewee.Model):
        user_id = peewee.AutoField()
        created = peewee.DateTimeField(default=datetime.datetime.now)
        last_login = peewee.DateTimeField(default=datetime.datetime.now)
        last_update = peewee.DateTimeField(default=datetime.datetime.now)
        last_ip = peewee.CharField(default="")
        username = peewee.CharField(default="", unique=True, index=True)
        password = peewee.CharField(default="")
        enabled = peewee.BooleanField(default=True)
        superuser = peewee.BooleanField(default=False)
        # we may need to revisit this
        api_token = peewee.CharField(default="", unique=True, index=True)

        class Meta:
            table_name = "users"
            database = db

    class TOTPData(peewee.Model):
        """Model for user TOTP methods.

        Consists of:
        UUID PK
        Foreign key user ID
        totp secret

        Args:
            BaseModel (_type_): _description_
        """

        id = peewee.CharField(primary_key=True, default="", index=True)
        name = peewee.CharField(default="TOTP")
        user = peewee.ForeignKeyField(Users, backref="totp_user")
        totp_secret = peewee.CharField()

        class Meta:
            table_name = "totp_data"
            database = db

    class TOTPRecovery(peewee.Model):
        """Model for user TOTP recovery.
        Consists of:
        UUID PK
        user_id foreign key field
        the recovery secret

        We will try to limit users to only 6 backup codes.

        Args:
            BaseModel (_type_): _description_
        """

        id = peewee.CharField(primary_key=True, default="", index=True)
        user = peewee.ForeignKeyField(Users, backref="totp_user")
        recovery_secret = peewee.CharField()

        class Meta:
            table_name = "totp_recovery"
            database = db

    migrator.create_table(TOTPRecovery)
    migrator.create_table(TOTPData)


def rollback(migrator, database, **kwargs):
    migrator.drop_table("totp_recovery")
    migrator.drop_table("totp_data")
    """
    Write your rollback migrations here.
    """
