# Generated by database migrator
import peewee
import datetime


def migrate(migrator, database, **kwargs):
    db = database

    class Users(peewee.Model):
        user_id = peewee.AutoField()

        class Meta:
            table_name = "users"
            database = db

    class PasskeyData(peewee.Model):
        id = peewee.CharField(primary_key=True, default="", index=True)
        name = peewee.CharField(default="Passkey")
        user = peewee.ForeignKeyField(Users, backref="passkey_user")
        credential_id = peewee.BlobField()
        public_key = peewee.BlobField()
        sign_count = peewee.IntegerField(default=0)
        transports = peewee.CharField(default="")
        device_type = peewee.CharField(default="")
        backed_up = peewee.BooleanField(default=False)
        created_at = peewee.DateTimeField(default=datetime.datetime.now)
        last_used_at = peewee.DateTimeField(null=True)

        class Meta:
            table_name = "passkey_data"
            database = db

    class PasskeyChallenge(peewee.Model):
        id = peewee.CharField(primary_key=True, default="", index=True)
        user = peewee.ForeignKeyField(Users, backref="passkey_challenge", null=True)
        challenge = peewee.BlobField()
        challenge_type = peewee.CharField()
        created_at = peewee.DateTimeField(default=datetime.datetime.now)
        expires_at = peewee.DateTimeField()

        class Meta:
            table_name = "passkey_challenges"
            database = db

    migrator.create_table(PasskeyData)
    migrator.create_table(PasskeyChallenge)


def rollback(migrator, database, **kwargs):
    migrator.drop_table("passkey_challenges")
    migrator.drop_table("passkey_data")
