# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns(
        "users", disable_password_auth=peewee.BooleanField(default=False)
    )


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("users", ["disable_password_auth"])
